## Basic Configuration

baseurl = "https://www.alkzar.cl/" 
builddrafts = false
canonifyurls = false
relativeURLs = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Crist칩bal Alc치zar"
title = "Crist칩bal Alc치zar"

theme = "hugo-goa"

## Hugo Built-in Features
enableEmoji = true
disqusShortname = "alkzar-cl" # Comment out to disable Disqus.
googleAnalytics = "UA-111580586-1"
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]


## Site Settings
[params]
author = "Crist칩bal Alc치zar"
intro = "游늴Easy to talk游늳"
#description = "Now @Pied Piper. Previously @Hacker Hostel, @Bachmanity and @Aviato. <br/> \"What is F times 5? It's Fleventy-five.\""
description = "hard to write ;) <br> dadas"
authorimage = "foto_perfil.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal Blog"
keywords = "alkzar, alkzar-blog, data-science, python, ggplot2, DataViz, R, TidyTuesday, tidyverse"

## Social Accounts
[params.social]
cv = "https://github.com/alcazar90/CRAL-CV/blob/f64dd3fdd5cf8d4940cae72c73edfa4f9e57fdac/examples/cv.pdf"
github = "/alcazar90"
instagram = "go.alcazar"
linkedin = "alcazar90"
twitter = "/vamos_alcazar"
stackoverflow = "5843243"
email = "alcazar.cristobal90@gmail.com"

## Extras
[params.extra]
copyright = "춸 2017. **Crist칩bal Alc치zar**. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/). <br/> Home Photo by Gabi ;)" 
#copyright = "춸 2017. **Crist칩bal Alc치zar**. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/). <br/> Home Photo by [Scott Walsh](https://unsplash.com/@outsighted) on [Unsplash](https://unsplash.com/)" 
poweredby = true
highlightjs = true

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
    
## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Learning Resources"
    identifier = "Learning Resources"
    weight = 300
    url = "/learning_resources/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
